x=input('enter the sequence 1')
y=input('enter the sequence 2')
Rxy=xcorr(x,y)
disp('cross corr is ')
disp(Rxy)
n1=length(x)
n2=length(y)
n3=length(Rxy)
N1=0:1:n1-1
N2=0:1:n2-1
N3=0:1:n3-1
subplot(1,3,1)
stem(N1,x)
xlabel('time')
ylabel('amplitude')
title('x(n)')
subplot(1,3,2)
stem(N2,y)
xlabel('time')
ylabel('amplitude')
subplot(1,3,3)
stem(N3,Rxy)
xlabel('time')
ylabel('amplitude')