fm=input('enter the message signal freq')
t=0:0.000005:0.05
fs=input('enter the sampling freq')
ts=1/fs
n=0:ts:0.05
xa=cos(2*pi*fm*t)
xs=cos(2*pi*fm*n)
subplot(1,4,1)
stem(t,xa)
xlabel('time')
ylabel('amplitude')
title('original signal')
subplot(1,4,2)
plot(t,xa,n,xs,'ro')
xlabel('time')
ylabel('amplitude')
title('combined signal')
subplot(1,4,3)
stem(n,xs)
xlabel('time')
ylabel('amplitude')
title('discreate signal')
subplot(1,4,4)
plot(n,xs)
xlabel('time')
ylabel('amplitude')
title('reconstructed signal')